### ISSUE TITLE
Delete does nothing

### ISSUE THREAD

**Issue by jpnielsen** [Bloodbat/Funes-Editors#1]
I was trying to delete a preset in a bank, using your funes editor
https://bloodbat.github.io/Funes-Editors/patch_bank.html

I can't delete - the mouse pointer displays a "prohibited sign = 🛇"  when the preset is moved onto the delete box in the bottom.
![image](https://github.com/user-attachments/assets/5271e173-63db-47f3-99fe-6d04df510119)

the same procedure works in the original webeditor
https://pichenettes.github.io/plaits-editor/patch_bank.html

same result in chrome and firefox

**Comment by Bloodbat** [comment]
Thanks for reporting :)

Fixed it, tried it with Firefox and Edge, can you please try it and let me know how it goes?

**Comment by jpnielsen** [comment]
"...  As the preset disappears, a shiver runs through the digital landscape, a silent testament to the loss of a potential masterpiece."

Works now.

**Comment by Bloodbat** [comment]
Thanks :)

Where's the quote from?

**Comment by jpnielsen** [comment]
Me playing with google gemini.

**Comment by Bloodbat** [comment]
Oh, ok, cool!
